// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjRNlG7T7rbC0YFDD2b-8KOo5QpkIWY_Q',
    appId: '1:167688123748:web:4d258e79db4eb18829b671',
    messagingSenderId: '167688123748',
    projectId: 'flutterpostapp-ca7d1',
    authDomain: 'flutterpostapp-ca7d1.firebaseapp.com',
    storageBucket: 'flutterpostapp-ca7d1.appspot.com',
    measurementId: 'G-VJ1WWZDYKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeEcBjPyXm-2qZG2_8x8N8pUhSJZ4LmA',
    appId: '1:167688123748:android:8c2bf3cbca2d1cc429b671',
    messagingSenderId: '167688123748',
    projectId: 'flutterpostapp-ca7d1',
    storageBucket: 'flutterpostapp-ca7d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQonAYi3G-_JUHXksOQnKXfCCtkQVpCQ',
    appId: '1:167688123748:ios:03366995d06292b529b671',
    messagingSenderId: '167688123748',
    projectId: 'flutterpostapp-ca7d1',
    storageBucket: 'flutterpostapp-ca7d1.appspot.com',
    iosClientId: '167688123748-8dhvbcoldueq7ij3lh8874v7jva210e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhQonAYi3G-_JUHXksOQnKXfCCtkQVpCQ',
    appId: '1:167688123748:ios:03366995d06292b529b671',
    messagingSenderId: '167688123748',
    projectId: 'flutterpostapp-ca7d1',
    storageBucket: 'flutterpostapp-ca7d1.appspot.com',
    iosClientId: '167688123748-8dhvbcoldueq7ij3lh8874v7jva210e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPostApp',
  );
}
